version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001" # Match the PORT from your .env file
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env # Specify your .env file
    command: npm run start:dev # Or your relevant start script
