name: CI/CD to AWS EC2 with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Test Docker Compose
      run: |
        docker compose -f docker-compose.yml config
        docker compose build
        docker compose up -d
        sleep 15
        docker ps
    - name: Tear Down Docker Containers
      run: docker compose down

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > /tmp/pro-key.pem
        chmod 600 /tmp/pro-key.pem

    - name: Add EC2 Host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy Files to EC2
      run: |
        scp -i /tmp/pro-key.pem -r . ubuntu@${{ secrets.EC2_HOST }}:/var/www/simoo-backend

    - name: Create .env File on EC2
      run: |
        ssh -i /tmp/pro-key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        echo "${{ secrets.ENV_VARS }}" > /var/www/simoo-backend/.env
        EOF

    - name: Deploy Application
      run: |
        ssh -i /tmp/pro-key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd /var/www/simoo-backend
        docker compose down || true
        docker compose up -d --build
        EOF
